config/routes.rb
Cha::Application.routes.draw do
  resources :harvests

  resources :typeteas

  resources :places

  resources :teas
  root to: 'teas#index'

end

app/models/tea.rb
class Tea < ActiveRecord::Base
  attr_accessible :hanzi_name, :harvest_id, :place_id, :presence, :price, :rus_name, :transliter_name, :typetea_id, :photo
  belongs_to :typetea
  belongs_to :harvest
  belongs_to :place

  has_attached_file :photo, :styles => { :small => "150x150" },
  											:storage => :dropbox,
										    :dropbox_credentials => Rails.root.join("config/dropbox.yml")										
 	 
end

app/models/tea_type.rb
class TeaType < ActiveRecord::Base
  attr_accessible :name
  has_many :teas, dependent: :destroy
end

app/controllers/teas_controller.rb
class TeasController < ApplicationController

	def index
    @teas = Tea.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @teas }
    end
  end

  def show
    @tea = Tea.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tea }
    end
  end

  def new
    @tea = Tea.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tea }
    end
  end

  def edit
    @tea = Tea.find(params[:id])
  end

  def create
    @tea = Tea.new(params[:tea])
    @tea.photo = params[:tea][:photo]
   

    respond_to do |format|
      if @tea.save
        format.html { redirect_to teas_path, notice: 'Cha was successfully created.' }
        format.json { render json: @tea, status: :created, location: @tea }
      else
        format.html { render action: "new" }
        format.json { render json: @tea.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @tea = Tea.find(params[:id])

    respond_to do |format|
      if @tea.update_attributes(params[:tea])
        format.html { redirect_to @tea, notice: 'Cha was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tea.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @tea = Tea.find(params[:id])
    @tea.destroy

    respond_to do |format|
      format.html { redirect_to teas_url }
      format.json { head :no_content }
    end
  end


end

app/helpers/teas_helper.rb
module TeasHelper
end

app/views/teas/_form.html.erb
<%= form_for @tea, :url => teas_path, :html => { :multipart => true } do |f| %>
  <% if @tea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tea.errors.count, "error") %> prohibited this tea from being saved:</h2>

      <ul>
      <% @tea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset>
    <legend>Фото</legend>
       <div class="field">
        <%= f.file_field :photo %>
       </div>
  </fieldset>


   <fieldset>
    <legend>Названия</legend>
        <table>
          <tr>
            <td>
              <div class="field">
                <%= f.label :hanzi_name %><br />
                <%= f.text_field :hanzi_name %>
              </div>
            </td>
            <td>
              <div class="field">
                <%= f.label :transliter_name %><br />
                <%= f.text_field :transliter_name %>
              </div>
            </td>
            <td>
              <div class="field">
                <%= f.label :rus_name %><br />
                <%= f.text_field :rus_name %>
              </div>
            </td>
          </tr>
        </table>
  </fieldset>

  <fieldset>
    <legend>Цена</legend>
       <div class="field">
        <%= f.number_field :price %>грн.
       </div>
  </fieldset>

   <fieldset>
    <legend>Наличие</legend>
       <div class="field">
          <%= f.check_box :presence %>
        </div>
  </fieldset>


  <fieldset>
    <legend>Место выращивания</legend>
        <div class="field">
          <%= f.select( :place_id, Place.find(:all).collect {|u| [u.name, u.id]}, :promt => 'Выбери место выращивания') %>
        </div>
        <div class="actions">
          <%= link_to 'Добавь новое место выращивания', new_place_path %>
        </div>
  </fieldset>

  <fieldset>
    <legend>Тип чая</legend>
        <div class="field">
          <%= f.select( :typetea_id, Typetea.find(:all).collect {|u| [u.name, u.id]}, :promt => 'Выбери тип чая') %>
        </div>
        <div class="actions">
          <%= link_to 'Добавь новый тип чая', new_typetea_path %>
        </div>
  </fieldset>

  <fieldset>
    <legend>Год сбора урожая</legend>
        <div class="field">
          <%= f.select( :harvest_id, Harvest.find(:all).collect {|u| [u.name, u.id]}, :promt => 'Выбери год урожая') %>
        </div>
        <div class="actions">
          <%= link_to 'Добавь другой год урожая', new_harvest_path %>
        </div>
  </fieldset>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teas/index.html.erb
<h1>Китайский чай:</h1>  

<% @teas.each do |tea| %>
    <table class="roundborder">
      <tr>
        <td class="cell_9"><%= image_tag tea.photo.url(:small) %></td>
        <td class="cell_1"><%= tea.hanzi_name %></td>
        <td class="cell_2"><%= tea.transliter_name %></td>
        <td class="cell_3"><%= tea.rus_name %></td>
        <td class="cell_4"><%= tea.price %></td>
        <td class="cell_5"><%= tea.typetea.name %></td>
        <td class="cell_6"><%= tea.presence %></td>
        <td class="cell_7"><%= tea.place.name %></td>
        <td class="cell_8"><%= tea.harvest.name %></td>
        <td class="cell_10"><%= link_to 'Edit', edit_tea_path(tea) %></td>
        <td class="cell_10"><%= link_to 'Destroy', tea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    </table>
    <br />
    
    <% end %>
    
   <br />

   

<div >
    <p class="buttonnewtea">
        <%= link_to "Добавить новый чай", new_tea_path, :class => "button"  %>
    </p>
    
</div>

       

app/views/teas/new.html.erb
<h1>New tea</h1>

<%= render 'form' %>

<%= link_to 'Back', teas_path %>

app/views/teas/show.html.erb
<p>
  <b>Name:</b>
  <%= @tea.name %>
</p>