config/routes.rb
Cha::Application.routes.draw do
  resources :harvests

  resources :typeteas

  resources :places

  resources :teas
  root to: 'teas#index'

end

app/models/typetea.rb
class Typetea < ActiveRecord::Base
  attr_accessible :name
  has_many :teas
end

app/controllers/typeteas_controller.rb
class TypeteasController < ApplicationController
  # GET /typeteas
  # GET /typeteas.json
  def index
    @typeteas = Typetea.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @typeteas }
    end
  end

  # GET /typeteas/1
  # GET /typeteas/1.json
  def show
    @typetea = Typetea.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @typetea }
    end
  end

  # GET /typeteas/new
  # GET /typeteas/new.json
  def new
    @typetea = Typetea.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @typetea }
    end
  end

  # GET /typeteas/1/edit
  def edit
    @typetea = Typetea.find(params[:id])
  end

  # POST /typeteas
  # POST /typeteas.json
  def create
    @typetea = Typetea.new(params[:typetea])

    respond_to do |format|
      if @typetea.save
        format.html { redirect_to new_tea_path(@tea), notice: 'Typetea was successfully created.' }
        format.json { render json: @typetea, status: :created, location: @typetea }
      else
        format.html { render action: "new" }
        format.json { render json: @typetea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /typeteas/1
  # PUT /typeteas/1.json
  def update
    @typetea = Typetea.find(params[:id])

    respond_to do |format|
      if @typetea.update_attributes(params[:typetea])
        format.html { redirect_to @typetea, notice: 'Typetea was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @typetea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /typeteas/1
  # DELETE /typeteas/1.json
  def destroy
    @typetea = Typetea.find(params[:id])
    @typetea.destroy

    respond_to do |format|
      format.html { redirect_to typeteas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/typeteas_helper.rb
module TypeteasHelper
end

app/views/typeteas/_form.html.erb
<%= form_for(@typetea) do |f| %>
  <% if @typetea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@typetea.errors.count, "error") %> prohibited this typetea from being saved:</h2>

      <ul>
      <% @typetea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/typeteas/edit.html.erb
<h1>Editing typetea</h1>

<%= render 'form' %>

<%= link_to 'Show', @typetea %> |
<%= link_to 'Back', typeteas_path %>

app/views/typeteas/index.html.erb
<h1>Listing typeteas</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @typeteas.each do |typetea| %>
  <tr>
    <td><%= typetea.name %></td>
    <td><%= link_to 'Show', typetea %></td>
    <td><%= link_to 'Edit', edit_typetea_path(typetea) %></td>
    <td><%= link_to 'Destroy', typetea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Typetea', new_typetea_path %>

app/views/typeteas/new.html.erb
<h1>New typetea</h1>

<%= render 'form' %>

<%= link_to 'Back', typeteas_path %>

app/views/typeteas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @typetea.name %>
</p>


<%= link_to 'Edit', edit_typetea_path(@typetea) %> |
<%= link_to 'Back', typeteas_path %>