config/routes.rb
Cha::Application.routes.draw do
  resources :harvests

  resources :typeteas

  resources :places

  resources :teas
  root to: 'teas#index'

end

app/models/harvest.rb
class Harvest < ActiveRecord::Base
  attr_accessible :name
  has_many :teas
end

app/controllers/harvests_controller.rb
class HarvestsController < ApplicationController
  # GET /harvests
  # GET /harvests.json
  def index
    @harvests = Harvest.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @harvests }
    end
  end

  # GET /harvests/1
  # GET /harvests/1.json
  def show
    @harvest = Harvest.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @harvest }
    end
  end

  # GET /harvests/new
  # GET /harvests/new.json
  def new
    @harvest = Harvest.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @harvest }
    end
  end

  # GET /harvests/1/edit
  def edit
    @harvest = Harvest.find(params[:id])
  end

  # POST /harvests
  # POST /harvests.json
  def create
    @harvest = Harvest.new(params[:harvest])

    respond_to do |format|
      if @harvest.save
        format.html { redirect_to new_tea_path(@tea), notice: 'Harvest was successfully created.' }
        format.json { render json: @harvest, status: :created, location: @harvest }
      else
        format.html { render action: "new" }
        format.json { render json: @harvest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /harvests/1
  # PUT /harvests/1.json
  def update
    @harvest = Harvest.find(params[:id])

    respond_to do |format|
      if @harvest.update_attributes(params[:harvest])
        format.html { redirect_to @harvest, notice: 'Harvest was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @harvest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /harvests/1
  # DELETE /harvests/1.json
  def destroy
    @harvest = Harvest.find(params[:id])
    @harvest.destroy

    respond_to do |format|
      format.html { redirect_to harvests_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/harvests_helper.rb
module HarvestsHelper
end

app/views/harvests/_form.html.erb
<%= form_for(@harvest) do |f| %>
  <% if @harvest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@harvest.errors.count, "error") %> prohibited this harvest from being saved:</h2>

      <ul>
      <% @harvest.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/harvests/edit.html.erb
<h1>Editing harvest</h1>

<%= render 'form' %>

<%= link_to 'Show', @harvest %> |
<%= link_to 'Back', harvests_path %>

app/views/harvests/index.html.erb
<h1>Listing harvests</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @harvests.each do |harvest| %>
  <tr>
    <td><%= harvest.name %></td>
    <td><%= link_to 'Show', harvest %></td>
    <td><%= link_to 'Edit', edit_harvest_path(harvest) %></td>
    <td><%= link_to 'Destroy', harvest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Harvest', new_harvest_path %>

app/views/harvests/new.html.erb
<h1>New harvest</h1>

<%= render 'form' %>

<%= link_to 'Back', harvests_path %>

app/views/harvests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @harvest.name %>
</p>


<%= link_to 'Edit', edit_harvest_path(@harvest) %> |
<%= link_to 'Back', harvests_path %>